apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: myphp
  name: myphp
spec:
  containers:
  - image: logcana.azurecr.io/myphp:latest
    name: myphp
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: myphp
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: myphp
  type: LoadBalancer
